stages:
  - test
  - build
variables:
  DOCKER_DRIVER: overlay

test:
  image: mhart/alpine-node:7
  services:
  - selenium/standalone-chrome:3.1.0
  stage: test
  variables:
    SELENIUM_GRID_ADDR: "selenium__standalone-chrome"
  script:
  - source ./scripts/gitlabci.sh
  - cd app
  - npm install
  - npm run karma

build:
  image: docker
  services:
  - docker:dind
  stage: build
  only:
  - develop
  script:
  - apk --no-cache add nodejs=6.9.2-r1
  - cd app
  - npm install
  - npm run docker:build
  - docker login -u hxuanhung -p uE3X63kt30wjdsaeFdlNPkQI7dcv
  - npm run docker:push
  - cd ../api
  - npm run docker:build
  - npm run docker:push
